name: Canary

on:
  push:
    branches: ["main"]


jobs:
  build-cli:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest]
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-go@v5
        with:
          go-version: 1.21.0 # The Go version to download (if necessary) and use.
      - name: Build CLI
        shell: bash
        run: |
          make build
          cp "build/jlaunch" "jlaunch-$RUNNER_OS"
      - uses: actions/upload-artifact@v4
        with:
          name: jlaunch-${{runner.os}}
          path: jlaunch-${{runner.os}}
  
  Release:
    needs:
      [build-cli]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: EndBug/latest-tag@latest
        with:
          # You can change the name of the tag with this input.
          # Default: 'latest'
          tag-name: canary
      - uses: actions/download-artifact@v4
        with:
          name: jlaunch-Linux
      - uses: actions/download-artifact@v4
        with:
          name: jlaunch-macOS
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          name: Canary
          tag_name: canary
          files: |
            jlaunch-macOS
            jlaunch-Linux
